### ISSUE TITLE
No Note is saved

### ISSUE THREAD

**Issue by Boumy** [dpap31/TimeClock#2]
Hello. Brillant idea this workflow. Thank you.
However, I can't succeed in adding a note for an "in" event. I mean, it is not saved in csv file.
Must the note be quoted or brackets ?
My try:
tc in mynote
doesn't save "mynote" in the csv
Thxs

**Comment by dpap31** [comment]
@Boumy - Thanks for opening an issue. The most recent PR (#3 ) should fix this issue. Let me know if you encounter any other issues.

**Comment by Boumy** [comment]
Excellent ! Thank you very much.
